### ISSUE TITLE
Window size & position not saved; default overlapped by taskbar

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#1]
_From @escalonn on December 23, 2014 12:4_

Running 1.3.7 on Windows x64, 1366x768 display.

* The CKAN.exe window always spawns aligned to the bottom of the screen, even if the taskbar does not auto‑hide. Hence the lowest part of the interface always starts covered by the taskbar.
* The window does not remember its position and size when last closed, so that the window must be manually resized on every launch. Its horizontal spawn position is not consistent, and I can’t detect a pattern, except that the window bottom is always aligned to the display bottom.

_Copied from original issue: KSP-CKAN/CKAN#679_

**Comment by Ippo343** [comment]
Too old, closing. If it's still relevant with newer releases, I'll reopen this. @escalonn

**Comment by escalonn** [comment]
Still present for me on 1.5.6.

**Comment by AlexanderDzhoganov** [comment]
Happy to say this has been fixed in v1.6.2 :)
