### ISSUE TITLE
CKAN Sort By Request

### ISSUE THREAD

**Issue by hmlafrance** [KSP-CKAN/CKAN-support#100]
Hello,

Hopefully I am not posting this in the wrong place but I am looking for a way to change the default "Sort By" for "Organizations" and "Groups" and at the very least from "Ascending" to "Descending" on the initial load. The end goal would be to order manually by our choosing.

I have been able to change the drop down but this does not change the grid order on the initial page load. I have also checked in the "groups.py" and "home.py" but so far I have been unsuccessful. 

Any direction would be much appreciated, thank you. We are running CKAN v2.2

**Comment by AlexanderDzhoganov** [comment]
Hey, I think you're looking for [the other CKAN project](https://github.com/ckan/ckan).
