### ISSUE TITLE
Need to Restart GUI App to Install More Mods

### ISSUE THREAD

**Issue by chasingcode** [KSP-CKAN/CKAN-support#101]
Using version 1.6.5.0-g, after clicking the Apply button and the selected mods are finished installing, the Changeset tab disappears, requiring the app to be closed and reopened to install any other mods.

**Comment by mgsdk** [comment]
The changeset tab does not reappear if you select/deselect any mods?

**Comment by chasingcode** [comment]
No, it doesn't reappear even if I select more mods to install.

**Comment by Dazpoet** [comment]
Does this problem persist in later versions? I'm unable to reproduce under Windows 7 using CKAN 1.6.10.

**Comment by pjf** [comment]
No response in 29 days, closing with the hopes the newer versions have fixed this. :)
