### ISSUE TITLE
"version" field does nothing in metapackages

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#102]
After playing around a bit with metapackages I noticed that the version field in them don't seem to have a function.

Creating a simple metapackage like

    {
    "spec_version": "v1.6",
    "identifier": "YourMetapackageName",
    "version": "1",
    "license": "unknown",
    "name": "User friendly name of your metapackage",
    "abstract": "A short description of the metapackage",
    "kind": "metapackage",
    "depends": [
        {
            "name": "ModuleManager",
            "version": "2.5.9"
        }
	]
    }

Will install the same version (2.5.10 as of this post) as this one

    {
    "spec_version": "v1.6",
    "identifier": "YourMetapackageName",
    "version": "1",
    "license": "unknown",
    "name": "User friendly name of your metapackage",
    "abstract": "A short description of the metapackage",
    "kind": "metapackage",
    "depends": [
        {
            "name": "ModuleManager",
        }
	]
    }

Not sure if this is by design or not but it's confusing to the end user (me) at least. I assume there might be times when you'd want a user to specifically install a certain version of a mod inside a metapackage and the current system makes it look like that would be possible but it isn't.

It should be noted that the installed-default.ckan file has the version fields so giving it a purpose would make that file a snapshot rather than the, perhaps, intended redistributable modlist it is now.

I propose that if the version field is made to distinctly install specific versions through the use of metapackages that the installed-default.ckan have those fields removed as to make it easier for end users to just grab that file and send to their friends.

**Comment by Ippo343** [comment]
This is absolutely not intended, and also very weird.
I will investigate asap (but keep in mind that right now my "asap" means ~2 weeks).

**Comment by Dazpoet** [comment]
Another thing about the versionfield, which might or might not be relevant, is that it seems to contain other things than the version.

A clean KSP with only FAR installed will have this installed-default.ckan

    {
"spec_version": "v1.6",
"identifier": "installed-default",
"version": "2015.03.14.10.22.27",
"license": "unknown",
"name": "installed-default",
"abstract": "A list of modules installed on the default KSP instance",
"kind": "metapackage",
"depends": [
    {
        "name": "AerodynamicModel",
        "version": "provided by FerramAerospaceResearch"
    },
    {
        "name": "FAR",
       {
"spec_version": "v1.6",
"identifier": "installed-default",
"version": "2015.03.14.10.22.27",
"license": "unknown",
"name": "installed-default",
"abstract": "A list of modules installed on the default KSP instance",
"kind": "metapackage",
"depends": [
    {
        "name": "AerodynamicModel",
        "version": "provided by FerramAerospaceResearch"
    },
    {
        "name": "FAR",
        "version": "provided by FerramAerospaceResearch"
    },
    {
        "name": "ModuleManager",
        "version": "2.5.10"
    },
    {
        "name": "FerramAerospaceResearch",
        "version": "v0.14.6"
    }
]
}
    },
    {
        "name": "ModuleManager",
        "version": "2.5.10"
    },
    {
        "name": "FerramAerospaceResearch",
        "version": "v0.14.6"
    }
]
    }

I'm pretty sure that `"provided by FerramAerospaceResearch"` isn't a version of something but maybe it's working as intended?

**Comment by JapaMala** [comment]
I can confirm this issue, and add that it has caused a lot of confusion for a multiplayer server I'm on.
The CKAN file specifies a specific RealFuels config, which needs to be selected to not cause problems, but CKAN does not respect that, and asks the user to chose a config, giving no indication as to which is the right one.
