### ISSUE TITLE
Trajectories-pre repository points to SCANsat-pre

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#105]
Adding the Trajectories-pre repo will give the option to install SCANsat-dev release rather than Trajectories-dev release, the latter is what I assume is the intended behaviour.

It seems the repo points to the wrong place based on ![picture](http://i.imgur.com/3XiHAUV.png)

I tried looking around in CKAN-meta-dev but must unfortunatly admit I have no idea about how to fix this problem.

**Comment by hakan42** [comment]
I believe the config file for this is directly on amsterdam.ksp-ckan.org ; I'll give it a look. 

Alternatively, you could look into the sources of Repository.cs in the CKAN-core repo, the URL to this file should be hard-coded somewhere in there.

**Comment by Dazpoet** [comment]
Well I looked around but it would appear my ability to understand the stuff anywhere but CKAN-meta and NetKAN is severly limited :(

**Comment by mgsdk** [comment]
The error is in the config file on the API server. Both SCANsat-pre and Trajectories-pre have the same uri. CKAN pulls the list in [CKAN-core/Types/Repository.cs:10](https://github.com/KSP-CKAN/CKAN-core/blob/master/Types/Repository.cs#L10)

Output from api.ksp-ckan.org at the time of writing:
```json
{
	"repositories": [
	{
		"name": "default",
		"uri": "https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip"
	},
	{
		"name": "Amsterdam mirror",
		"uri": "http://amsterdam.ksp-ckan.org/master.zip"
	},
	{
		"name": "dev",
		"uri": "https://github.com/KSP-CKAN/CKAN-meta-dev/archive/master.zip"
	},
	{
		"name": "MechJeb2-dev",
		"uri": "https://github.com/KSP-CKAN/CKAN-meta-dev/archive/MechJeb2-ci.zip"
	},
	{
		"name": "RemoteTech-pre",
		"uri": "https://github.com/KSP-CKAN/CKAN-meta-dev/archive/RemoteTech-pre.zip"
	},
	{
		"name": "SCANsat-pre",
		"uri": "https://github.com/KSP-CKAN/CKAN-meta-dev/archive/SCANsat-pre.zip"
	},
	{
		"name": "Trajectories-pre",
		"uri": "https://github.com/KSP-CKAN/CKAN-meta-dev/archive/SCANsat-pre.zip"
	}
]
}
```

**Comment by hakan42** [comment]
Fixed. For the record, the file is /var/ckan/api/mirrors on amsterdam.ksp-ckan.org
