### ISSUE TITLE
[Suggestion]Remove all mod before Install from ckan file

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#108]
_From @ryohpops on  25 mar 2015 05:47 CET_

It would be nice that all mods are uninstalled previously when you try to install a .ckan file.

I'm sharing .ckan meta package with players on a multi-player mod server to sync mod installation.
Also I'm switching current mod-set via meta packages to play several universe with each mod environment.
In order to keep correct mod environment (no version conflict, no unnecessary mod), I remove all mods by hand firstly.

I suggest that it should be automated or configurable.
Leaving mod's config on a mod removal works fine in this situation as well.

_Copied from original issue: https://github.com/KSP-CKAN/CKAN/issues/796_

**Comment by Dazpoet** [comment]
I think the solution to your problem would be multiple KSP installs so you wouldn't have to constantly switch mod-set?

A problem with removing all mods prior to the install of a .ckan file is that the recommended way of addings mods to CKAN include testing them by installing them manually. Also some people might be running their own hacked together .ckan files for various reasons and this feature would kill that possibility.

A better solution might be the ability to add some way to remove all installed mods in a simple manner? Something like `ckan remove --all`?

**Comment by ryohpops** [comment]
Thank you for your reply and sorry for my repo mistake.

I never thought to have multiple KSP installations!
That seems the simplest solution and I understand that the way I said can cause more cons than pros.

A method to manipulate all mods in one action still sounds useful.
Just placing some button or check box that selects/deselects all might be enough.

**Comment by Dazpoet** [comment]
The [new version](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.6.6) includes removing with matches to regular expressions.

My knowledge of regular expressions is just about none but I'd hazard a guess that there exists a way of choosing everything?

**Comment by ryohpops** [comment]
Regular expression option is good news.

I reconsidered about select/deselect all on GUI and I think it's not necessary based on multiple KSP installation.
There is a CUI way, that's enough :)

So please close this issue, thank you very much!
