### ISSUE TITLE
Question about netiquette around closing old issues

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#110]
Being very unfamiliar with github and after looking around here for a bit I have a question about netiquette.

Looking around the various repos there are some issues that seem somewhat unnecessary, outdated or are pure duplicates of eachother. Some examples would be:

- https://github.com/KSP-CKAN/CKAN/issues/384
- https://github.com/KSP-CKAN/CKAN-core/issues/63
- https://github.com/KSP-CKAN/CKAN/issues/385
- https://github.com/KSP-CKAN/CKAN-support/issues/30

Is it ok to close these (and/or request they be closed) or are issues not closed by their authors always assumed to be relevant for as long as they stay open?

**Comment by Ippo343** [comment]
Hey Daz! When an issue is not relevant, you can close it safely. E.g, KSP-CKAN/CKAN-core#63 could be closed safely.
When it's an outdated support request (for example, regarding an old version) I usually close it and also poke the author, so they have a chance to make me re-open it if it's still relevant.

**Comment by pjf** [comment]
Exactly what @Ippo343 said! :)

I'm now closing this as answered. Please feel free to re-open this if there's more discussion needed. :)

Keep being awesome!

~ Paul
