### ISSUE TITLE
WebException and CKAN-GUI giving 401 Unauthorized errors

### ISSUE THREAD

**Issue by Rhapsodyy** [KSP-CKAN/CKAN-support#113]
Hiya

Recently found your mod to manage mods and it seems awesome so great work.
However im having an issue getting it to run, ive had a look through your wiki and help pages and cant seem to find a solution for the issue i was wondering if you could help.

Ive put the .exe file in my KSP root file which is on my e: drive when i go to run the program it starts and lets me select my ksp directory, but then whenever it tries to do anything im getting a 401 error. Below i have copy/pasted the error text im receiving in the hope this helps provide a solution:

Thanks in advance for any help you can provide, Rhapsodyy

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at CKAN.AutoUpdate.MakeRequest(Uri url)
   at CKAN.AutoUpdate.FetchLatestCkanVersion()
   at CKAN.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue.  If you click quit the application will close immediately.

The remote server returned an error: (401) Unauthorized

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///E:/Users/Matt/Steam/SteamLibrary/SteamApps/common/Kerbal%20Space%20Program/ckan.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.18331 built by: FX45GDRSTAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18331
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by PatrickInLaw** [comment]
I have the exact same error message (Remote Server Returned an Error: (401) Unauthorized.)

What I did: 
1. Downloaded CKAN
2. Ran CKAN.exe
3. Selected my .90 installation of KSP (in the standard c:/... SteamApps/ ... directory)
4. Got the error. 

The CKAN directory was created in my KSP directory, with three files (GUIConfig.xml, installed-default.ckan, and registry.json) and a subdirectory (downloads, which is empty) there.

This is my first time installing CKAN, so it was a clean install.

Hope that helps!

-Patrick

**Comment by ashjack** [comment]
I have the exact same issue as PatrickInLaw, with absolutely no differences in what I did.

**Comment by PatrickInLaw** [comment]
This appears to be limited to the GUI. I copied CKAN.exe into the main KSP directory (where ksp.exe is located, not GameData), then ran it from the console, and i can do everything right there. It has successfully scanned all of my installed mods, downloaded a list of available mods, and displayed that list. However, when i then try to run the GUI, I get the (401) error again.

**Comment by MInorInconvenience** [comment]
I am having the extract same problem (Win8.1).  Funny thing is, I have used it successfully for months.  It just started this in the past few days.  I am thinking there was a Windows Update that changed .NET somehow.

**Comment by PatrickInLaw** [comment]
I don't think it was a windows update - I haven't updated my system in a while, and definitely haven't updated .NET. Maybe a server-side update that doesn't like the way the GUI sends a connection string?

**Comment by PatrickInLaw** [comment]
WORKAROUND: 

1. Edit the GUIConfig.xml file to have the auto-update flags as this:
<CheckForUpdatesOnLaunch>false</CheckForUpdatesOnLaunch>
<CheckForUpdatesOnLaunchNoNag>true</CheckForUpdatesOnLaunchNoNag>

2. if the auto-update dialog pops up, hit the red "x" button in the top right corner (don't choose one of the options).

3. It should now work.

**Comment by Dazpoet** [comment]
No new version of CKAN is installed without asking for it. It seems something changed on the GitHub side. As it seems commandline is working another workaround is probably to use commandline for now. I'm trying to get ahold of the CKAN-GUI maindeveloper as we speak.

**Comment by MInorInconvenience** [comment]
PatrickInLaw, your workaround did the trick!  Many thanks.

**Comment by doktorjet** [comment]
1.6.5 is still the most stable and unglitchy build.
And it allows working PartManager.

**Comment by Dazpoet** [comment]
Is this problem Windows only? Can someone confirm or deny the existance of the issue on Linux (together with distro) and OS X? Please also add the output from `mono --version` in your Linux and/or OS X install.

**Comment by Dazpoet** [comment]
Someone on irc thought [this](https://github.com/KSP-CKAN/CKAN-core/blob/45bed693db7ab47a6be5d3c3f6feba8953104b2d/Net/AutoUpdate.cs#L98) might be the problem.

One of the closed duplicates of this issue confirmed that the problem also exists on OS X.

**Comment by zlsa** [comment]
Same issue on Arch Linux. `mono --version`:
```
Mono JIT compiler version 3.12.1 (tarball Thu Mar 12 06:31:20 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

In addition, `ckan help` shows it being version `0.0.0.0`.

**Comment by pjf** [comment]
So it looks like https://github.com/KSP-CKAN/CKAN-core/pull/83 added a github token to the request headers, but there's no explanation in the commit as to *why*, nor whose token it actually is. I wouldn't be surprised if it's since been revoked.

@AlexanderDzhoganov , if you're about, can you comment?

**Comment by pjf** [comment]
I can confirm that removing KSP-CKAN/CKAN-core#83 resolves this.

I'm building a new client now.
