### ISSUE TITLE
Jenkins went belly up

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#118]
He's complaining about not having a workspace, whatever that means.

According to wiki I should ping @pjf and @AlexanderDzhoganov for Jenkins things and Jenkins himself adds @hakan42 to the list so here goes :)

**Comment by pjf** [comment]
Gosh dang it, investigating now.

**Comment by pjf** [comment]
If I'm reading http://ci.ksp-ckan.org:8080/job/Prerelease_Inflator_-_ModuleManager/jobConfigHistory/ correctly, then @hakan42  changed the jenkins configs at about the same time that we started seeing these problems. I'm currently looking over github issues to try and find if there's any documentation on what was changed or why.

@hakan42 , if you're around, your input would be very much appreciated.

**Comment by pjf** [comment]
Farking fark. The disk on the ci machine is full. That's likely what's causing all this. :/

**Comment by pjf** [comment]
I've freed some disk space on the machine by pruning the number of jenkins backups in older months.

```
root@ksp-ckan:~/jenkins_backup# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G   19G   17M 100% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            235M  4.0K  235M   1% /dev
tmpfs            50M  348K   49M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            246M     0  246M   0% /run/shm
none            100M     0  100M   0% /run/user
root@ksp-ckan:~/jenkins_backup# rm -rf FULL-2015-01-1[124-9]_00-00
root@ksp-ckan:~/jenkins_backup# rm -rf FULL-2015-01-2[124-9]_00-00
root@ksp-ckan:~/jenkins_backup# rm -rf FULL-2015-02-0[124-9]_00-00
root@ksp-ckan:~/jenkins_backup# rm -rf FULL-2015-02-[012][124-9]_00-00
root@ksp-ckan:~/jenkins_backup# rm -rf FULL-2015-03-[012][124-9]_00-00
root@ksp-ckan:~/jenkins_backup# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G   18G  1.5G  93% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            235M  4.0K  235M   1% /dev
tmpfs            50M  348K   49M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            246M     0  246M   0% /run/shm
none            100M     0  100M   0% /run/user
```

**Comment by techman83** [comment]
We could probably just chuck them into an S3 bucket with a retention policy. Probably no good reason to store them locally.

**Comment by pjf** [comment]
@techman83 : Yeah. A major overhaul of the CI system is *very* high on my priority list. As with almost everything CKAN related that isn't working as it should, it's a matter of finding enough cycles to get the work done. :(

**Comment by techman83** [comment]
@pjf - totally. Is there a list of these kind of tasks that one could take a look at. It'd be awesome to allow you to focus on the code stuff, where as some of these tasks could totally be done by someone with not enough cycles to learn C# :)

**Comment by pjf** [comment]
As far as I can tell the jenkins jobs haven't restarted. @hakan42, @AlexanderDzhoganov, if either of you are around I'd love input. My inclination is to bump the [number of executors](http://ci.ksp-ckan.org:8080/computer/%28master%29/configure) to '1' (it's currently zero), but the jenkins documentation suggests that zero is fine if jenkins is farming jobs out to docker slaves, which I understand we are.

**Comment by pjf** [comment]
Yay! We're clearing the job queue, and I have no idea why.

I *did* stop a particularly old (and definitely not current) docker container via [the docker control panel](http://ci.ksp-ckan.org:8080/docker-plugin/server/Docker%20Slave%201/), but have no idea if that actually prompted any changes or not.

**Comment by techman83** [comment]
Win!

**Comment by hakan42** [comment]
The number of executors must stay at zero so any and all build jobs will be running on the docker slave instead of on the master. Changing that would have opened up the CI machine to any number of attacks throught the build.sh scripts we trust fully.

But @pjf found the solution already :smiling_imp:

**Comment by pjf** [comment]
Yay! @hakan42 is here!

What was my solution? Freeing up disk space, obviously, do you know if my killing of a docker container was at all related to the jobs starting to clear again, or did they just spontaneously restart?

**Comment by hakan42** [comment]
It was cleaning up the docker containers...

And by the way, I am not here, this is only my ghost speaking. The main me is busy repairing the fallout after a major server center crash with $MAXINT people breathing down his neck...

**Comment by Dazpoet** [comment]
Resolved and so I'm closing this.

**Comment by Dazpoet** [comment]
aaaand it's happening again :P

**Comment by hakan42** [comment]
Went to "Jenkins Management", stopped all docker instances that were hanging since the last 6 days, and now the jobs started being picked up.

**Comment by mgsdk** [comment]
Jenkins hasn't picked up any jobs for a few hours now, and currently has a queue of 8 pending jobs.

**Comment by hakan42** [comment]
Gave the Docker slaves a swift kick in the posterior... They are picking up new jobs again now.

Please re-open if / when things go south again.

**Comment by Dazpoet** [comment]
It's happening again it seems, 2 jobs stuck in queue for some 5-10 odd minutes and I'm guessing more to come.

Is it just me or does this happen more often now?

**Comment by hakan42** [comment]
It might happen more often as amount of work increases and therefore more docker children have to be started / reaped. I have seen similar effects on another project of mine.

Unfortunately, I won't be able to work on this for the next few hours, no full computer nearby...

**Comment by techman83** [comment]
It's out of space again. I'll try and nudge it. After I get the indexing stuff sorted I'll start on moving it to AWS.

**Comment by Dazpoet** [comment]
From what I understand space should now be available but it doesn't seem to be doing anything

**Comment by Dazpoet** [comment]
It's aliiiiive :D
