### ISSUE TITLE
"UP" arrow keys don't navigate mod list properly

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/CKAN-support#119]
This is obviously only a "1 star" bug, but the "up" arrow keys doesn't work reliably.

"Down" works as expected: it changes the selection to the mod below the one currently selected.
"Up", however, doesn't respect the filter. So, if I set the filter to "New in repository" (which shows all of the mods for some reason) it works as expected. If I set the filter to "All" (which only shows compatible mods), **"up" will not move the selection bar if there is a hidden/filtered mod above the selector.**

Example:
The first three mods in my "all"(compatible only) list are 6s Service Compartment Tubes, Action Groups Extended, and Actions Everywhere. The first several mods in "New in repository"(which displays all of them) are 6s, Kerbal Christmas, AGE, and AE. Everything works correctly in "New in Repo" view.
In all/compatible view, however: I can press "down" to move the blue selection bar thing from 6s to AGE, and again to move from AGE to AE (as expected). Also, I can press "up" to move from AE to AGE (as expected). However, I cannot press up to move from AGE to 6S. This seems to be because "Kerbal Christmas" is in between AGE and 6s, even though Kerbal Christmas is hidden in my current view. This occurs any time I try to use "up" when there is a filtered/hidden mod above the one I have selected.

I'm confident that I have identified how to replicate the issue, but I'm not sure my explanation come across well, so please ask if it is unclear. I am running Arch Linux.

**Comment by mgsdk** [comment]
For anyone else investigating this: I've tried to add a KeyDown eventhandler to the ModList to catch the arrowkeys, but while the event fires I am not able to override the default behavior.

**Comment by RichardLake** [comment]
mgsdk - What OS are you using? I've tried to replicate this on windows and can not. It may be a mono bug ...

**Comment by mgsdk** [comment]
This may be a Mono only bug, as I am on Linux (Arch to be specific) with Mono 3.12.1. @RichardLake so you have no issues with the up and down arrows on Windows? It may be a big Mono patch I've just submitted then...

**Comment by RichardLake** [comment]
Just replicated in a Linux mint VM pointing to the same install as the windows version. Definitely a mono bug.

**Comment by RichardLake** [comment]
Should be fixed in the latest nightly.
