### ISSUE TITLE
Several mods are out of date

### ISSUE THREAD

**Issue by bstpierr** [KSP-CKAN/CKAN-support#122]
Of the mods I am attempting to install the following ones appear out of date:

- ActiveTextureManagement: http://forum.kerbalspaceprogram.com/threads/59005
- ScienceAlert: http://forum.kerbalspaceprogram.com/threads/76793
- RealChute: http://forum.kerbalspaceprogram.com/threads/57988

**Comment by Dazpoet** [comment]
Resolved
