### ISSUE TITLE
Active Texture Management Out of Date

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN-support#124]
From the CKAN UI client, I'm seeing Active Texture Management versions 4.3, whereas 5.0 is the latest release.  I'm also showing x86 and x64 versions for 1.0, which isn't really valid anymore, as there is no 1.0 x64 client.

4.3 is causing side effects in KSP 1.0, like eating all the flags.

Links:
http://forum.kerbalspaceprogram.com/threads/59005
https://github.com/rbray89/ActiveTextureManagement/releases/tag/5-0

**Comment by Dazpoet** [comment]
I've asked in the thread for clarification on how to distribute these packages. There very much still exists a 64bit client for linux users.

I'll look into killing off the current listings since they're obviously wrong.

**Comment by Dazpoet** [comment]
Resolved, 5.0 now properly shows up in CKAN.
