### ISSUE TITLE
Old version of TweakScale offered for KSP v1.0 installs

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-support#125]
Version 1.5 of TweakScale is offered to KSP v1.0 installs, this version is 4 versions behind the current (2.0). I believe this is because subsequent versions have a hard requirement of `"ksp_version": "0.90"` whereas 1.5 only has a requirement of `"ksp_version_min": "0.25"`.

The newest version (2.0), while having a constraint of `"ksp_version": "1.0"` also removes the `v` that was in previous version numbers (`2.0` vs. `v1.5`). I believe CKAN performs some variant of a lexicographical sort, which puts `2.0` as being older than `v1.5`. KSP-CKAN/CKAN#715 would solve this issue as `vercmp` successfully compares `2.0` as being *after* `v1.5`.

I don't know what the best solution is at the moment (manually updating the `2.0` to be `v2.0`?), just raising the issue.

**Comment by Dazpoet** [comment]
manually adding a ksp_version_max 0.90 in 1.5 should resolve this issue and provide an upgrade path for 1.0 users

**Comment by dbent** [comment]
> manually adding a ksp_version_max 0.90 in 1.5 should resolve this issue and provide an upgrade path for 1.0 users

`"ksp_version_max": "0.90"` would also have to be added to prior versions (`v1.44`, `v1.47`, `v1.48`) as well.

> EDIT: Hoping that CKAN handles any version compat as an upgrade, else we're in trouble!

Good question. Naively, I would actually expect CKAN to refuse to upgrade from a "higher" version to a "lower" version, even if the "lower" version is compatible and the "higher" version is not.

**Comment by Dazpoet** [comment]
Aye, the best solution by a landslide would be to have the author push an upgrade like v2.0.1 that changes nothing but adds a `v` for compatibility reasons.

**Comment by pellinor0** [comment]
I'll fix it with a new version, thanks for the analysis!

**Comment by Dazpoet** [comment]
Our indexing bot should find it soon'ish, it does a round every hour or so and should find this on the next one.

**Comment by dbent** [comment]
The update went through, I went to go check it, didn't appear; turns out KSP just updated to v1.0.1. :smile:

**Comment by Dazpoet** [comment]
Showing properly in CKAN, I'm closing this issue and thanks @dbent for reporting it and @pellinor0 for helping us fix it without hacky workarounds :D
