### ISSUE TITLE
Feature Request: Export/Import of Installed Mods

### ISSUE THREAD

**Issue by SkyMarshal** [KSP-CKAN/CKAN-support#128]
It's mildly irritating to manually select the same set of mods I always use when I have a new KSP install (be it for another computer or simply because I am an idiot and bricked my current install).

Preferably, it should have a choice in the drop-down menu in the GUI for import/export, and a set of commands for the same for the CLI.  I don't really care the exact version of the mods exported/imported, so long as on import it installs those that are compatible while informing me of which mods are not, if at all possible.

**Comment by mgsdk** [comment]
I believe the CLI has the functionality already, in that it exports a list of all currently installed mods in "installed-default.ckan". I am not sure if there is any way to do the installation in the GUI at the moment, but you should be able to do it with the CLI using "ckan.exe install -c /path/to/installed-default.ckan".

**Comment by SkyMarshal** [comment]
That's... really handy, actually.  I will try that on my laptop when I next get a chance, which will probably be in a few hours.

**Comment by Dazpoet** [comment]
the installed-default.ckan file is always around seeing as it's basically a list of what's installed. See https://github.com/KSP-CKAN/CKAN-support/wiki/Sharing-a-modlist-%28metapackages%29

**Comment by Ippo343** [comment]
If you don't mind, I'm gonna close this one :)

**Comment by SkyMarshal** [comment]
Fine by me, thanks!
