### ISSUE TITLE
New version of kerbal engineer not showing

### ISSUE THREAD

**Issue by akasurak** [KSP-CKAN/CKAN-support#129]
The new engineer isn't showing in ckan, and it's been several days. As per the FAQ I am posting here. (actually several mods aren't showing as updated, for me also: realchute, smartstage, stagerecovery, TACfuelbalancer, MKS), but they report via KSP-AVC.

(linux, most recent ckan)

**Comment by akasurak** [comment]
Strange, restarting ckan fixed this. I'd had it up and running for a few days.

**Comment by Dazpoet** [comment]
Did you remember to refresh?

**Comment by akasurak** [comment]
Yes. Several times

**Comment by Dazpoet** [comment]
Are they all working now?

**Comment by akasurak** [comment]
Yes, it seems to be
