### ISSUE TITLE
CKAN doesn't pass commandline arguments to KSP

### ISSUE THREAD

**Issue by playful1510** [KSP-CKAN/CKAN-support#131]
I have noticed that if I try to have CKAN pass arguments to KSP, they don't make it in. For example, my current CKAN command-line arguments are "KSP.exe -popupwindow" without quotes. KSP still doesn't act like it's in a borderless window, even though it should be getting the argument to start as a borderless window.

**Comment by Farlo** [comment]
I'm getting the same issue.

**Comment by mgsdk** [comment]
I am unable to reproduce this on Linux. Is this on Windows with CKAN 1.6.13?

**Comment by playful1510** [comment]
Unsure about 1.6.13, was occurring on windows 1.6.12. Haven't tested .13

**Comment by mgsdk** [comment]
I believe there was some launcher code updates in 1.6.13, but it might only have been for OS X. Else, someone on Windows need to dig into this to debug it.

**Comment by playful1510** [comment]
Testing now.

**Comment by playful1510** [comment]
Still minimizes when clicked out of. Reproduced on windows 1.6.13

**Comment by mgsdk** [comment]
Right, will probably need someone who develops on Windows to look into this.
