### ISSUE TITLE
Ckan won't let let update mods

### ISSUE THREAD

**Issue by patton446** [KSP-CKAN/CKAN-support#138]
whenever I try to update my mods, it gives me following text in gui prompt
About to remove:

Done!

```
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/Firespitter/Plugins, it's not empty
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/Firespitter, it's not empty
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/TriggerTech/KerbalAlarmClock, it's not empty
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/TriggerTech/TransferWindowPlanner, it's not empty
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/UmbraSpaceIndustries/Kolonization/Assets, it's not empty
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/UmbraSpaceIndustries/Kolonization, it's not empty
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/UmbraSpaceIndustries, it's not empty
Not removing directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/UmbraSpaceIndustries, it's not empty
```

**Comment by mgsdk** [comment]
Can you tell us the content of those folders? It might just be some residual configuration files.

**Comment by Dazpoet** [comment]
Also, what mods are you removing? If multiple mods reside in Folder X they will all print that they are not removing Folder X until the last mod residing in it is removed, and the last one will remove the folder.

Say you have MKS/OKS and FTT installed and then remove both, the first one will then print that it does not remove the USI folder but the second one will remove it.

**Comment by patton446** [comment]
no i'm trying to update them, not remove them. the gui gives you the option to "mark all updated" which tries to all mods installed to the new version

**Comment by pjf** [comment]
We should probably suppress these messages as they're confusing. The upgrade process looks like this:

- Start a transaction
- Remove the previous versions of the mods
- Install the new versions of the mods
- Commit the changes if success.

Part of the 'removal' process is to remove directories if they're empty. If they're not (which is the norm; because they can contain configuration files or other mods) then we don't try to delete them.

I'll drop the message priority on these down so they're no longer visible unless you're running in verbose mode.

**Comment by pjf** [comment]
Closing for now with a PR to hide diagnostic messages in future clients.

@patton446 , if you think I've done this in error, simply post here and we'll re-open it.
