### ISSUE TITLE
Memory Estimate

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN-support#140]
Could you add a column to the GUI and a command line reporter that will estimate the memory required for a mod?  Even  if there is no automated way to test this, the mod files could just have a way to plug in numbers from tested installs.  This would give us poor folk who run KSP at maximum memory an indication of which mods are most affecting our footprint.

**Comment by dbent** [comment]
Deriving memory usage for any piece of software is hugely complicated and any single number listed would be grossly misleading. The end result would just be a huge amount of angst as people complain and argue about an, effectively, arbitrary number.
