### ISSUE TITLE
In 1.6.14, the "Go to changes" button doesn't activate

### ISSUE THREAD

**Issue by BlackSoldierB** [KSP-CKAN/CKAN-support#141]
When you check/uncheck a checkbox in the GUI, the "Go to changes" button will no longer activate.
In version 1.6.13 this does still work.

**Comment by Dazpoet** [comment]
Could you expand on what you expect to happen and what happens and give reproduction steps?

**Comment by BlackSoldierB** [comment]
The first picture is the start situation. Notice that the first checkbox is uncheck and that "Go to changes" button is not activated.
![ckan 141 before check](https://cloud.githubusercontent.com/assets/2544928/7553710/7dbccefc-f708-11e4-8f60-82b24808b7a6.PNG)

In the picture below, is the first checkbox checked, but the "Go to changes" button didn't activate. 
![ckan 141 after check](https://cloud.githubusercontent.com/assets/2544928/7553711/804d1302-f708-11e4-9a78-a215681b0b56.PNG)

**Comment by mgsdk** [comment]
Could you upload your registry.json and installed-default.ckan somewhere?

**Comment by pjf** [comment]
I have exactly the same problem, which is ironic, because I'm the one who made the release.

**Comment by pjf** [comment]
I suspect KSP-CKAN/CKAN-GUI#109 may be behind this, but that's nothing more than a hunch at this stage.

**Comment by pjf** [comment]
> Could you upload your registry.json and installed-default.ckan somewhere?

[registry.json](https://dl.dropboxusercontent.com/u/9702672/KSP/registry.json.gz)

We're on IRC debugging this now. :)

**Comment by pjf** [comment]
v1.6.15 released should fix this. It does for me, and I was hitting the same problems. :)

If it doesn't, let me know and I'll re-open.
