### ISSUE TITLE
CKAN GUI won't open on Mint

### ISSUE THREAD

**Issue by marce155** [KSP-CKAN/CKAN-support#142]
**As requested by mgsdk:**
I'm trying to run CKAN (1.6.15 [.14,.13]) on Linux Mint 17 with mono 4.0.1.
The CLI works fine, but the GUI won't show. No error messages.

What I tried so far:
- check Window Pos settings - they are at 0,0 (I even tried 800,600 just to be sure)
- start in debug mode which resulted in a harmless looking log http://hastebin.com/risojofaga.coffee 
- looked through the troubleshooting page and made sure the openssl lib is installed

If you need more information tell me what to do and I'll provide it if I find some free time.

**Comment by pjf** [comment]
> I'm trying to run CKAN (1.6.15 [.14,.13]) on Linux Mint 17 with mono 4.0.1.

Just to check, does this imply it *used* to work with 1.6.12?

**Comment by RichardLake** [comment]
Just tried on a Linux Mint 17.1 64 bit with mono 4.0.1. Seems to work.

**Comment by RichardLake** [comment]
Was fixed by using a GUIConfig from me. Maybe the autoupdate was hanging? Either way we need more logging calls in the GUI startup. It would of really helped here.
