### ISSUE TITLE
Cannot switch between mods with the same provides

### ISSUE THREAD

**Issue by mgsdk** [KSP-CKAN/CKAN-support#144]
Install a virtual package like Astronomers Pack, go with the default selection. Now, try to change the selection, for instance reducing the graphical quality of the clouds package, by selecting the low edition and deselecting the high edition. The changeset tab does not appear.

**Comment by RichardLake** [comment]
https://github.com/KSP-CKAN/CKAN-core/pull/116 and https://github.com/KSP-CKAN/CKAN-GUI/pull/111 should solve this.
