### ISSUE TITLE
Application Error with CKAN-GUI

### ISSUE THREAD

**Issue by blshell18** [KSP-CKAN/CKAN-support#146]
I keep getting a an application error whenever i click refresh to update the mod list. It says:

The instruction at 0x7741ce1b referenced memory at 0xffffffff.  The memory could not be read. Click on OK to terminate the program.

i am also experiencing an issue where I open the GUI and wait approximately 3 seconds and it will close on its own, without any errors or notifications.  

Any help will be much appreciated, thank you

**Comment by mgsdk** [comment]
Which OS are you running CKAN on? Do you know the version of CKAN you are running?

**Comment by blshell18** [comment]
Win 7 Ultimate SP1 and i believe it would be  Callisto
