### ISSUE TITLE
Upgrade of mods results in FileExistsKraken

### ISSUE THREAD

**Issue by mgsdk** [KSP-CKAN/CKAN-support#149]
Reported on behalf of MelancholyFlapper on IRC.

Output from CKAN is available at https://github.com/mgsdk/CKAN-support-files/blob/master/MelancholyFlapper/output.txt.
Registry is available at https://github.com/mgsdk/CKAN-support-files/blob/master/MelancholyFlapper/registry.json.

Seems to be an issue with Bahamuto.

**Comment by Dazpoet** [comment]
Thought I had fixed this, which mods where being updated?

**Comment by mgsdk** [comment]
40 are marked as upgradeable in the registry, among these is BahamutoD. I'm assuming MelacholyFlapper was attempting to upgrade them all in one go.
