### ISSUE TITLE
Ampyear mod is 2 versions behind

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN-support#151]
the CKAN version of AMP Year is 0.14 however 0.16 is available for manual installs.

**Comment by Dazpoet** [comment]
Interesting, looking at the .netkan file it should be working. It seems the newer versions have a capital `V` instead of a lower case though which might be affecting what CKAN is showing. We have properly indexed `V0.16a` as the latest version but it's not showing up.

**Comment by Dazpoet** [comment]
Aha, also reported earlier it seems at https://github.com/KSP-CKAN/CKAN-support/issues/147
