### ISSUE TITLE
CKAN doesn't even start properly 

### ISSUE THREAD

**Issue by MPvDgamer** [KSP-CKAN/CKAN-support#153]
when I want to run the ckan.exe it simply doesn't start. and then a text comes up saying:

C:\Windows\system32\RichEd20.DLL is eithernot designed to run on 
Windows or it contains an error. Try installing the program again using 
the original installation media or contact your system administrator or 
the software vendor for support.

and after that it stops running. what should I do now?

**Comment by Dazpoet** [comment]
I'm confused as to how you're even getting a connection with whatever that .dll file is. Please explain step by step how you ended up getting that error.

Where did you download CKAN, where on your harddrive is it, where on your harddrive is your ksp installation, how are you attempting to start CKAN and does the text appearing say anything except the thing you wrote above?

Seems the RichEd20.dll file has something to with outlook and/or rich text editing, not sure how this affects CKAN. See https://support.microsoft.com/en-us/kb/291651

**Comment by MPvDgamer** [comment]
*I downloaded the "ckan.exe" it from the release page on GitHub. 
*after the download it goes in the downloads file.
*my KSP is directly under the Hard Disk ( C: ). 
*I double click the ckan.exe  to run the program and then it gives me that message after a couple of seconds.


the release page: https://github.com/KSP-CKAN/CKAN/releases/tag/v1.6.16

**Comment by Dazpoet** [comment]
I have no idea how you're getting errors with a unrelated .dll. Does CKAN call it or some function originating from it maybe? @RichardLake do you have any clue?

**Comment by mgsdk** [comment]
Any errors if you try to run the non-GUI version, for instance
```
ckan.exe available
```
in a terminal/command prompt?
