### ISSUE TITLE
Allow removal/overwriting of autodetected/existing mods.

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#17]
_From @cerebrate on December 18, 2014 23:11_

It's something of a pain to have to manually delete AD'ed mods which weren't previously in CKAN but now are (or when first starting to use CKAN) to replace them with CKANed versions, or to upgrade them. While difficult to do reliably automatically, I think it'd be useful enough to be worth the work.

Also handy at times like these (KSP upgrades) when one ends up installing lots of mods that are in the database as 0.25 compatible but which work on 0.90, and which may take days or weeks for the metadata to catch up.

_Copied from original issue: KSP-CKAN/CKAN#631_

**Comment by thor79** [comment]
This is a huge issue for me. As I play with a lot of mods, being able to manage them effectively is important. So I use CKAN. Problem is...CKAN doesn't handle auto-detected mods well. Copying mods from another install (and copying over the CKAN folder from that install) does not work as CKAN detects all those mods as auto-detected...so I can't do anything with the mods. These two features need to be added. Right now you are hurting your user experience by refusing to do anything with mods you detect as "AD". You would not need a migration plugin to solve issues with AD mods if you would allow us to overwrite (by downloading latest using CKAN) or remove AD mods.
