### ISSUE TITLE
[feature request] Add 'disable' and 'enable' commands

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#19]
_From @ToxicFrog on December 17, 2014 0:35_

It's often convenient to be able to "temporarily" uninstall a mod (for example, when updating KSP) without actually removing it from the mod list. At present this can only be done by removing the mod and keeping a separate list yourself, or by manually deleting the mod files and then reinstalling it with CKAN next time you want it. A "ckan disable" command that uninstalls the mod while keeping an entry for it in the registry of installed mods, and a "ckan enable" command that enables (by reinstalling) a disabled mod, would be nice.

_Copied from original issue: KSP-CKAN/CKAN#608_

**Comment by AlexanderDzhoganov** [comment]
This is something for CKAN 2.0, where we hopefully run VFS (like Skyrim Mod Manager) so this would be trivial.

**Comment by Ippo343** [comment]
>VFS

Hi guys, did I miss a cool memo? :P
________________________________
Da: Alexander Dzhoganov<mailto:notifications@github.com>
Inviato: ‎04/‎03/‎2015 17:42
A: KSP-CKAN/CKAN-support<mailto:CKAN-support@noreply.github.com>
Cc: Michele<mailto:m.ippolito@outlook.com>
Oggetto: Re: [CKAN-support] [feature request] Add 'disable' and 'enable' commands (#19)

This is something for CKAN 2.0, where we hopefully run VFS (like Skyrim Mod Manager) so this would be trivial.

---
