### ISSUE TITLE
On Ubuntu, "Choose another KSP install" kills gui, opens ckan.exe in default program

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#2]
_From @politas on December 23, 2014 7:13_

With KSP 1.3.7 on Ubuntu 14.04, when I select "Settings -> Choose another KSP install", it opens ckan.exe in Archive Manager by default (and closes the ckan gui). Doesn't matter whether I have a default set, or whether I have multiple instances. Closing the Archive Manager window leaves me with no gui. 

If I tweak Ubuntu so that it laubches .exe files with Mono, the CKAN gui closes and a new instance is spawned, which, if I have a default instance, opens that. 

Whatever happens with the launch of ckan.exe, the previous "mono ckan.exe" is still running in the background, with a gui and without a way to close it.

_Copied from original issue: KSP-CKAN/CKAN#677_

**Comment by Ippo343** [comment]
Hey @politas , is this still happening with the latest release? Closing in the meantime.

**Comment by politas** [comment]
Still happening with CKAN 1.5.6

22633 ?        S      0:00          \_ /bin/sh /home/politas/Desktop/KSP/CKAN
22634 ?        Sl     0:07          |   \_ mono /home/politas/Desktop/KSP/ckan/ckan.exe
22676 ?        Sl     0:06          \_ mono /mnt/SSD/KSP/ckan/ckan.exe

**Comment by Ippo343** [comment]
Reopening then :)

**Comment by mgsdk** [comment]
I seem to circumvent this problem by making two changes to the code in CKAN-GUI/SettingsDialog.cs.

1. Change the way the new process is started by setting the flag ```useShellExecute = false```.
2. Force application exit by using ```Environment.Exit(0)```.

```Application.Exit()``` may not work because we are not exiting a thread somewhere (At least from what I can glance on the net), but I can't seem to find any manually created threads.

Code is available at https://github.com/mgsdk/CKAN-GUI/tree/ckan_support_issue_2.

**Comment by politas** [comment]
Still happening with ckan 1.6.0

**Comment by politas** [comment]
Ok, that update has changed the behaviour slightly. Now, the new appplication window doesn't open, and the previous mono instance is left running. Sorry, 1.6.1 has made it worse, not fixed it.

**Comment by mgsdk** [comment]
The patch works for me in Linux. I will give 1.6.1 a go and see if there is some interaction with the patch.

System information: Arch Linux (64 bit), running Mono 3.12.0.

**Comment by mgsdk** [comment]
In my local build I do not get the error, but I do get the error you (@politas) describe with the 1.6.1 release.  I'll try and transition to the official build scripts to see if I can find the cause.

**Comment by mgsdk** [comment]
After help from @AlexanderDzhoganov it seems to be related to ckan.exe missing the executable flag.

**Comment by politas** [comment]
Sorry, I've been busy, so I missed a few versions. I am seeing this as definitely fixed in CKAN 1.6.5
