### ISSUE TITLE
Refresh the repository the first time running the GUI

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#22]
_From @adamplumb on December 8, 2014 1:22_

I just got this installed and at first when I didn't see any mods loaded it took me a while to figure out what to do.  Then I tried the "Refresh" button, and that did get the mods listed.  You may want to either make it clear what the "Refresh" button refreshes and/or run the refresh command the first time the user runs the GUI so they have a list of mods shown to them right away.

_Copied from original issue: KSP-CKAN/CKAN#534_

**Comment by Dazpoet** [comment]
Although it's not the exact thing asked for I have updated the [user guide](https://github.com/KSP-CKAN/CKAN-support/wiki/User-guide) with pictures to further reflect that one must click the "Refresh" button to get the list of mods in the first place.

Considering that a refresh takes a few seconds (at least for me) and "freeze" the client for that time having it run automagically the first time might prompt the user to believe it has crashed?
