### ISSUE TITLE
Error: Unhandled exception:

### ISSUE THREAD

**Issue by maninspace** [KSP-CKAN/CKAN-support#37]
"System.IO.IOException: The Process cannot access the file D:\...\CdFileMgr\93982915-31f3-41.tmp" because it is used by another process.
System.IO.__Error.WinIOError(Int32 error Code, String maybe FullPath)
by System.IO.File.InternalDelete(String path,"

It is all that the error window shows. I am getting this message since the last update regularly. After dismissing the whole program crashes

**Comment by AlexanderDzhoganov** [comment]
Closing this as there has been no response for several days, if you still have problems please make a new issue.
