### ISSUE TITLE
Proposal: Synchronize CKAN mod lists between installations

### ISSUE THREAD

**Issue by Eddlm** [KSP-CKAN/CKAN-support#39]
From http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-5-0-24-Dec-2014?p=1638484&viewfull=1#post1638484

CKAN could have a way to export a modlist to a file so other instances of CKAN could import that file and install the exact same list of mods on another KSP installation. It could help to synchronize modlists between different KSP installations, allowing them to have the same mods installed.

Situations in wich this could be helpful/useful:
   1. People who need to reinstall KSP. Having a list of mods for CKAN to import, download and install would ease the process of leaving the new KSP like the old one was.
   2. People (like me) who wish to keep two KSP installations synchroniced (mod-wise). For example, a main PC installation and a laptop installation.
   3. Youtubers wich have the "What mods I used" thing could replace enormous modlists with a simple link to a CKAN mod synchronization file.
   4. It could allow people to make "modpacks" in form of exported modlists (A "realism overhaul" modlist, a "Exploration" modlist, etc), wich they could post somewhere for others to download and let CKAN handle it for them.

   That way of handling modpacks could help avoid the "NO REDISTRIBUTION" problem wich some mods have, preventing people from adding them to modpacks. As CKAN, when downloading mods, uses the original links the author provided, there's no "no redistribution" rule infringement.
 In this situation CKAN could also become a "modpack installer", basically.

**Comment by Eddlm** [comment]
MMh, I don't really see the difficulty. In fact, as CKAN has all the mods separated in different files, something along the lines of
$ckan list > list.txt
$for /f %%mod in list.txt do ckan install %%mod
could work.
It wont as ckan list puts more info than simply the installed mod identifiers...

I don't know how to code for CKAN, but the idea should be simple. A new command wich exports the installed mods to a plain text mods.ckan file, and a command wich loads identifiers from mods.ckan and installs them. We would be using already existing CKAN features (the default ckan mod installing procedure).

At least, this would work for the commandline mode. The GUI mode would do the same, but adding a window to select wich mods.ckan file you want to load.

**Comment by AlexanderDzhoganov** [comment]
@Eddlm we want to solve this in a much more controlled way, by having CKAN export a meta-package that depends on all of your mods (and their specific versions maybe?). This is a much more flexible approach than what you're proposing and as we've already discussed this a thousand times and have decided that this will happen sooner or later I see no reason to continue this discussion :) If you want to directly influence the development of this feature, please move your issue to CKAN-core. In the meantime I'm closing this.
