### ISSUE TITLE
A few suggestions/questions about CKAN for KSP

### ISSUE THREAD

**Issue by awsempredalien** [KSP-CKAN/CKAN-support#44]
To whomever this may concern,
I would just like to know why in the "Installed" column I can see the following: 
    1. Check-box
    2. The letters "AD"
    3. The symbol "-" (only shows up in the following filter categories: Installed, New In Repository, Not Installed, Incompatible).

Also is it possible for me to be able to launch/update the repository/refresh CKAN and have a list of mods already selected so that all I have to do is click "Launch KSP" without having to fiddle around with knowing which mods I am using?

**Comment by Ippo343** [comment]
Hi!

1. The checkbox is used to select (or deselect) a mod that you wish to install (or uninstall). After you have made your selection, click on the blue icon "Go to changes" to review the changes and accept them to install (or remove) the mods you selected.
2. It stands for Auto Detected: it means that mod is installed, but was no installed using CKAN. CKAN will *not* manage those mods, but it knows they are there.
3. It's replaced by another checkbox if an update is available for that mod.

When you open CKAN all the mods that you have installed using the client will be already selected. Remember to apply the changes before you launch KSP: ckan is not going to install anything until you accept the changes.
