### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by gewone1** [KSP-CKAN/CKAN-support#45]
i have tried to install ckan for about 1 hour now and i just can't figure out how to install it(Mac OS X 10.10). could someone give me a bit more detailed explanation?

**Comment by AlexanderDzhoganov** [comment]
Have you [checked the wiki](https://github.com/KSP-CKAN/CKAN-support/wiki/Installing-CKAN-on-OSX)?

**Comment by gewone1** [comment]
Yes I have but that did not work

**Comment by AlexanderDzhoganov** [comment]
You're going to have to explain what issues exactly are you encountering

**Comment by AlexanderDzhoganov** [comment]
Closing this as there's been no response for several days, if your problem is not solved please make a new issue.
