### ISSUE TITLE
Can not launch KSP through CKAN

### ISSUE THREAD

**Issue by MrRazerWolf** [KSP-CKAN/CKAN-support#48]
I recently installed CKAN and installed the mods just fine and all of that, but when I hit the launch KSP button it says "Couldn't start KSP. The system cannot find the file specified." Am I missing a step here or something?

**Comment by AlexanderDzhoganov** [comment]
Go to Settings -> KSP command- line and set it to `KSP.exe`

**Comment by MrRazerWolf** [comment]
Thank you
