### ISSUE TITLE
Unhandled Exception when upgrading Kerbal Alarm Clock

### ISSUE THREAD

**Issue by briang** [KSP-CKAN/CKAN-support#50]
I have Kerbal Alarm Clock v3.1.2 installed using CKAN. When I try to upgrade it to 3.1.3 using CKAN I get an Unhandled Exception (details [here](https://gist.github.com/briang/033dc23e0e9addb30c22)). This is reproducable and does not happen when I try to upgrade any other mods.

KSP 0.90 (Steam)
CKAN 1.5.2 (GUI)
Windows 7 64bit

Edit: Not fixed by CKAN 1.5.3
Edit^2: Moved errorlog to a gist

**Comment by hakan42** [comment]
The CKAN registry doesn't hold the "suggests" reference anymore.

**Comment by briang** [comment]
The issue was fixed prior to 1.5.6, probably since the "suggests" reference  was removed.
