### ISSUE TITLE
"Can't upgrade Toolbar, it is not installed" error when updating mod that recommends Toolbar

### ISSUE THREAD

**Issue by BasharMilesTeg** [KSP-CKAN/CKAN-support#51]
I encountered an [error](https://gist.github.com/BasharMilesTeg/20fe531b24aa63667daa) whilst trying to update Action Groups Extended 1.2.8a to 1.2.8b and Kerbal Alarm Clock v3.1.1.0 to v3.1.2.0 using the GUI (v1.5.3). I clicked Refresh before attempting to update and do not have Toolbar installed, nor did it show on the Changeset screen. [registry](https://app.box.com/s/z30lkm95wmqa9dh189jo)

**Comment by hakan42** [comment]
The CKAN registry doesn't hold the "suggests" reference anymore.

**Comment by BasharMilesTeg** [comment]
I removed Action Groups Extended and installed it again to work-around the crash but I'm continuing to get this [error](https://gist.github.com/BasharMilesTeg/9904a17213d5c80dd067), this time while updating AGExt to 1.2.8c and SmartStage to v2.5.0. I had clicked 'Refresh' to look for updates and do not have Toolbar installed, nor did it show on the Changeset screen. [registry](https://app.box.com/s/z30lkm95wmqa9dh189jo)

**Comment by BasharMilesTeg** [comment]
[CKAN-nightly-199](https://github.com/KSP-CKAN/CKAN-nightly/releases/tag/jenkins-CKAN-199) fixed this for me. WooHoo!
