### ISSUE TITLE
BlackTippedNosecone/WTFPL

### ISSUE THREAD

**Issue by harryyoung** [KSP-CKAN/CKAN-support#54]
https://github.com/KSP-CKAN/CKAN-meta/blob/master/BlackTippedNosecone/BlackTippedNosecone-1.0.ckan

Apparently BlackTippedNosecone causes an exception error on updates, It sais WTFPL is not a valid license and aborts the pull.

**Comment by hakan42** [comment]
which ckan version are you using? The WTFPL license is a pretty new addition, so please try again with 1.5.6 and re-open this ticket if it does not solve your problem.
