### ISSUE TITLE
Adding dev repositories gives double mods in the modlist

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#55]
Not sure if this is a feature or not but I'l report it and see what happens.

I added the dev repositories for MechJeb2 and SCANsat and now my modlist in CKAN looks as follows:

Double MechJeb2, one being labeled as "-DEV RELEASE"
https://mediacru.sh/t_1svqywFJ__

Double SCANsat, both being labeled as "-DEV RELEASE"
https://mediacru.sh/iM2T8Lw586rM

I would assume that it could be confusing for users when different dev-repos to add different behaviours in the same program. To get MJ dev versions I needed to uninstall my old mod and install the dev version. To get the dev version of SCAN I could just update the one I already had to the latest dev-version in CKAN.

This occurs on both my Windows 7 and OS X (10.10) computers, both running CKAN 1.5.6.

**Comment by hakan42** [comment]
Could you upload your registry.json somewhere and send me the link please?

**Comment by hakan42** [comment]
This was caused by our netkan-bot putting the files into the wrong directory...

@AlexanderDzhoganov , it's been the http://ci.ksp-ckan.org:8080/job/Prerelease_Inflator_-_MechJeb2/ job, I have remove the ckans from the wrong directories.

should be o.k. now, but you need to "update" or "refresh" your once more to see the effects.

**Comment by Dazpoet** [comment]
Where would I find this registry.json file, should it still be needed?

After a refresh both mods now show the behaviour of MJ in my first post. However a new issue arised which I made an issue report for here https://github.com/KSP-CKAN/CKAN-support/issues/56

**Comment by hakan42** [comment]
The registry.json file is usually in your KSP directory, in a subdirectory called "CKAN". You would also find your download cache and a file called "installed-default.ckan" there...

**Comment by Dazpoet** [comment]
This problem is resolved since some time, I'm closing the issue :+1:
