### ISSUE TITLE
Dev release of scansat does not count as dependency for scansat mission pack

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#56]
When uninstalling scansat via CKAN it also uninstalls the scansat mission pack, which seems very reasonable considering the latter cannot work without the former, so far so good.

After installing the dev release of scansat I can no longer install the mission pack, upon selection of that mod no "Changeset" tab occurs nor does it give me any reason for not doing so. If I uninstall scansat - dev and then select the mission pack again it brings up the Changeset tab and correctly lists scansat as a dependency.

Issue occurs with CKAN 1.5.6 in a Windows 7 environment.

**Comment by hakan42** [comment]
Yep, just noticed the same myself :smiling_imp:

**Comment by hakan42** [comment]
Freshly created metadata of the SCANsat-dev and MechJeb2-dev repos should allow for installation of the ContractConfigurator-files now.
