### ISSUE TITLE
Bug with new ATM mod files refusing to install

### ISSUE THREAD

**Issue by GlenSkunk** [KSP-CKAN/CKAN-support#57]
A bit of an odd issue here - I recently updated my repository to see what new mods were available, and it turns out that Active Texture Management got changed about. Unfortunately, it also removed the old Teonlight versions of Active Texture Management; a bit stupidly, I did not deactivate the Teonlight version of ATM before attempting to install the new rby89 versions. This has the effect of making it so I can't install the rby89 version, since it still sees the Teonlight version as owning the folder, but it also means I can't uninstall the Teonlight version because it no longer shows up in CKAN's mod list. Manually deleting the ATM folder doesn't help; that just makes the error change. The error as it stands now is like so:

About to remove:

Done!

About to install...

 * ActiveTextureManagement-x86-Aggressive 4-3 (cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/ActiveTextureManagement/ActiveTextureManagerConfig.cfg
Installing Mod : ActiveTextureManagement-x86-Aggressive 4-3
Owning Mod     : ActiveTextureManagement
CKAN Version   : v1.5.6-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

Any help would be appreciated. Apologies if I put this in an incorrect place.

**Comment by AlexanderDzhoganov** [comment]
Hey, we forgot to mark the new ATMs as conflicts to the old ones :(
Please try this [plugin](http://forum.kerbalspaceprogram.com/threads/106636-CKAN-plugin-Migration-Tool-v1-1-%28alpha%29-Clean-install-auto-detected-mods) and see if you can get the old ATM restored properly by using it, then repeat the procedure (delete old ATM, install new one).

**Comment by GlenSkunk** [comment]
Well, I tried that - unfortunately, it appears that the migration plugin isn't recognizing the ATM install I have; it certainly isn't showing up in any event. Bit of a worry, that.

**Comment by Dazpoet** [comment]
ping me if this is still an issue, I'm closing this for now.
