### ISSUE TITLE
[ubuntu] Locating KSP install in hidden folder

### ISSUE THREAD

**Issue by JamesFaraday** [KSP-CKAN/CKAN-support#58]
(I feel like I am missing something, but have searched and gone over existing bugs I can't find a solution. Sorry if I missed something)

Steam on Ubuntu by default installed KSP in "home/[username]/.local/share/Steam/steamapps/common/Kerbal Space Program". Notice that 'local' is a hidden folder. CKAN does not auto detect this location. Furthermore, the file browser does not seem to support selecting hidden folders. This combo makes it impossible to direct CKAN to the KSP install. 

I have rebooted and re-downloaded CKAN to no avail. I am on a hours old fresh install of Ubuntu 14.04 with the latest Steam and KSP version.

Suggested fixes. 
1. If possible, enable the file browser to see hidden folders. 
2. Allow the user to manually enter the path to KSP in plain text. 
3. Look for KSP install in said location as it is the default install location for Steam on Ubuntu.

**Comment by AlexanderDzhoganov** [comment]
Hey, you can easily add a KSP install from the command- line. Try:
```
ckan.exe ksp add default "<path to KSP>"
ckan.exe ksp default default
```

**Comment by JamesFaraday** [comment]
So the commands posted above need to be prefixed with 'mono', at least so far as Ubuntu is concerned. Other then that, they work fine. I still suggest some gui based way of locating a KSP install in a hidden folder. For now, mentioning this problem and solution on the forum/wiki would be good.

**Comment by hakan42** [comment]
Beg your pardon, but is the handling of hidden folders not part of the operating system?

The best we could do would be a hint in the wiki about how to configure some of the more widely used file browsers, but especially on Linux, you can never cover *all* of them...

**Comment by JamesFaraday** [comment]
The default file browser on Ubuntu does give you a way to see hidden folders. However, the file browser CKAN pops up to select the KSP install location does not use it. It seems as though it is using a mono specific one as the browser looks quite different.

**Comment by amedee** [comment]
This is NOT an issue in CKAN or in Linux, but an issue in .NET/Mono. However a workaround inside CKAN is possible. Google for "show hidden files in mono" turns up some interesting results, like this one:

> mono's (2.10.1 and git) System.IO.Directory.EnumerateFiles() does show 
> hidden or read-only files; MS .NET does show all files.
> 
> The reason for this is that read-only/hidden files do not have the FileAttributes.Normal bit set, 
> which comes from the Win32 API (my emphasis):
> 
> FILE_ATTRIBUTE_NORMAL:
>      A file that does not have other attributes set.
>      *This attribute is valid only when used alone.*"
> 
> So:
> normal    -> FileAttributes.Normal
> ro        -> FileAttributes.ReadOnly
> hidden    -> FileAttributes.Hidden
> hidden/ro -> FileAttributes.Hidden | FileAttributes.ReadOnly
> 
> but:
> directory/ro -> FileAttributes.Directory | FileAttributes.ReadOnly
> 
> (Which seems dumb: 'Normal' is the file type, like 'Directory' or 'Device'; 'ReadOnly', 'Hidden', 
> 'System', 'Encrypted' are additional attributes.  But that's beside the point.)

http://lists.ximian.com/pipermail/mono-list/2011-March/046708.html

I would suggest that development asks for further advice on StackOverflow and tags the question with Mono.
