### ISSUE TITLE
The Contributing section of the wiki needs to be re-written.

### ISSUE THREAD

**Issue by leftler** [KSP-CKAN/CKAN-support#59]
Now that the project has been split in to seperate sub-projects https://github.com/KSP-CKAN/CKAN-support/wiki/Workflow is no longer correct. Performing `git remote add upstream https://github.com/KSP-CKAN/CKAN.git` nolonger does anything because `KSP-CKAN` does not hold any code anymore.

We need instructions how to set up all of the various parts of the build environment so we can get a working build.

**Comment by mgsdk** [comment]
I've tried to bring the page up to date. Would appreciate someone else looking at the new page to catch any quirks.
