### ISSUE TITLE
Active Texture management

### ISSUE THREAD

**Issue by ChaozFlame** [KSP-CKAN/CKAN-support#60]
About to install...

 * ActiveTextureManagement-x86-Basic 4-3 (cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/ActiveTextureManagement/ActiveTextureManagerConfig.cfg
Installing Mod : ActiveTextureManagement-x86-Basic 4-3
Owning Mod     : ActiveTextureManagement
CKAN Version   : v1.5.6-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

The problem is that the active texture management folder is present inside gamedata but isnt being detected by ckan? It doesnt show up as installed.
I was planning to uninstall it and get the aggressive version instead since all the mods are realy eating up ram haha

**Comment by ChaozFlame** [comment]
oh right uhm originally i installed it via ckan but after i went to 1.5.6 from 1.5.0 it hasnt detected active texture management

**Comment by ChaozFlame** [comment]
i have also tried the plugin that in a previous post 2 days ago about this issue and it has not solved the problem

**Comment by BlackSoldierB** [comment]
Can you remove it using the command line? That's how i fixed this issue. PS: This is an duplicate issue.
See [this issue](https://github.com/KSP-CKAN/CKAN-support/issues/57)

**Comment by Dazpoet** [comment]
This should no longer be an active problem, ATM metadata has been stable for a long time now so I'm closing this.
