### ISSUE TITLE
Outer Planets Mod doesn't have full download

### ISSUE THREAD

**Issue by ntwest** [KSP-CKAN/CKAN-support#61]
The CKAN "outer planets mod" doesn't contain all of the necessary files for installing it (the Koperincus directory in particular, but most of the rest of the OPM download as well).

**Comment by Ippo343** [comment]
Poking @hakan42 , since I see he added those TODOs in the file.

**Comment by Dazpoet** [comment]
Resolved by https://github.com/KSP-CKAN/NetKAN/pull/979
