### ISSUE TITLE
CKAN - Universal Storage v1.0.90.1 metadata

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN-support#62]
Homepage is missing http:// prefix (clicking on the link defaults to file://, at least under Linux)

Package depends on Regolith package - which is not required if downloading manually.

**Comment by mgsdk** [comment]
Universal Storage includes Regolith in the manually downloaded zip file. CKAN simply pulls in the Regolith package instead of installing it from the Universal Storage zip file.

I have the same issue with the homepage link, will see if I can hunt it down in the netkan code.

**Comment by mwerle** [comment]
Apologies re regolith - I just got back from extended absence and now see that US has changed quite a bit. Please ignore that part of the bug report :)

**Comment by mgsdk** [comment]
No worries, and I think I have found the other issue as well now. Thanks for the report.
