### ISSUE TITLE
[Feature Request] Location of cache folder

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN-support#64]
It would be nice to be able to specify the location of the cache folder for the downloads.
This would also avoid duplicate downloads when managing multiple KSP installs.

**Comment by mgsdk** [comment]
Seems to be a duplicate of https://github.com/KSP-CKAN/CKAN-core/issues/10, though it doesn't specifically mention the possibility of changing the cache location.

**Comment by mwerle** [comment]
Yes, duplicate - someone mentioned being able to override the OS-default location in one of the comments.  Thanks for the link, and apologies for not checking more thoroughly first.

**Comment by mgsdk** [comment]
With the way the project is split up, things can be buried several places. Rather open a request and close it than not open it at all.
