### ISSUE TITLE
Issue with KAS and Universal Storage

### ISSUE THREAD

**Issue by Jencen** [KSP-CKAN/CKAN-support#65]
Hi
I get this error when trying to install Universal Storage and Universal Storage-KAS

"Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.6-0-g0000000 (beta)

Your GameData has been returned to its original state."

**Comment by mgsdk** [comment]
Universal Storage no longer need the addon packs, but contain all the functionality in the core pack. You should only need to install Universal Storage.

**Comment by hakan42** [comment]
A "Deprecated" ckan version is being generated just now, which allows your installation to continue successfully.
