### ISSUE TITLE
RCSBuildAid latest version is 0.5.5

### ISSUE THREAD

**Issue by BlackSoldierB** [KSP-CKAN/CKAN-support#66]
RCSBuildAid has been updated to 0.5.5 but is stuck on version 0.5.4 (again).
It is using [github](https://github.com/m4v/RCSBuildAid/releases). Shouldn't it automatically update?

**Comment by hakan42** [comment]
I can't find a RCSBuildAid netkan file. It seems like that the previous versions referenced curse, for which we have no automation yet.

I'll write up a netkan that points to your github repository.

**Comment by hakan42** [comment]
O.k., github netkan is written up, it fails though because your repo has no releases yet.

could you compare with https://github.com/S-C-A-N/SCANsat/releases which can be successfully indexed? Whenever your repo shows successful releases, they will be indexed within the hour.
