### ISSUE TITLE
Jenkins: install "zip" on the docker image

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN-support#69]
To work on the self-updating CKAN ideas, I need to be able to create zip archives on Jenkins (ckan.zip holding ckan.exe and netkan.zip holding netkan.exe, basically).

@AlexanderDzhoganov , pinging you via github issue as I don't have irc access at the moment :blush:

**Comment by hakan42** [comment]
Prerequisite for #30,

**Comment by hakan42** [comment]
Notice for @AlexanderDzhoganov : I put a slightly hackish way of obtaining a zip binary into the http://ci.ksp-ckan.org:8080/job/CKAN/ build job.

Feel free to kill it with atomic fire from orbit whenever you install a zip directly into the docker image :smiling_imp:

**Comment by AlexanderDzhoganov** [comment]
Fixed.
