### ISSUE TITLE
GUI shows provided modules as actually installed.

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#71]
I run the DEV version of SCANsat through CKAN and while doing so regular SCANsat also shows as installed. I suspect this might be due to https://github.com/KSP-CKAN/CKAN-support/issues/56 but I'm not sure. However regular SCANsat asks for an update straight of the bat after installing the DEV version, which can be seen here http://imgur.com/5JwAhAj

Trying to run the update for SCANsat throws the following Exception:

```
************** Exception Text **************
The following inconsistecies were found:
SCANsat-dev conflicts with SCANsat.   at CKAN.SanityChecker.EnforceConsistency(IEnumerable`1 modules, IEnumerable`1 dlls)
   at CKAN.RelationshipResolver..ctor(ICollection`1 modules, RelationshipResolverOptions options, Registry registry, KSPVersion kspversion)
   at CKAN.ModuleInstaller.Upgrade(IEnumerable`1 identifiers, NetAsyncDownloader netAsyncDownloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
This is done on CKAN 1.5.6, Win 7 64bit with CKAN standard repository, MJ dev repository and SCANsat dev repository.

**Comment by Dazpoet** [comment]
I'm guessing you'll want the .json so I finally found a way to get it onto the internet. Hoping this'll work http://puu.sh/f4ciz/f6b0789290.json

**Comment by pjf** [comment]
From IRC discussions, it sounds like the GUI is calling `Registry.Installed()` (which returns all mods installed, *including* those which are provided by another mod), but it should be called `Registry.Installed(false)`, which only returns actual modules installed.

Consequently, provided mods (which are not themselves installed) are showing as installed in the GUI. This is a bug.

**Comment by Dazpoet** [comment]
To reproduce this problem;

1) get a clean install of KSP
2) start CKAN
3) add SCANsat-pre repository
4) Install SCANsat - DEV RELEASE
5) attempt to update SCANsat via the GUI
