### ISSUE TITLE
No way in ckan to 'forget' ksp installs that are moved or deleted outside of ckan 

### ISSUE THREAD

**Issue by tjanke42** [KSP-CKAN/CKAN-support#72]
Example:

1. Add two KSP installs to CKAN - e.g. KSP-A and KSP-B.

2. Decide you no longer want KSP-B, delete its folder.

3. List the installs - 'ckan.exe ksp list' 
    - CKAN complains that KSP-B is not a valid install  (error message is "WARN CKAN.KSPManager (null) - KSP-B at <path> is not a valid install", where <path> is the path to the missing install).
    - only install KSP-A is listed

4. (Try to) tell CKAN to forget the missing install:
    - "ckan.exe ksp forget KSP-B"
       - response is "Couldn't find install with name KSP-B, aborting"

5. CKAN will continue to complain about the missing install, but will not allow you to 'forget' it

To resolve my version of this problem, I had to go into the windows registry, HKEY_CURRENT_USERS\Software\CKAN, delete the offending KSPInstanceName & KSPInstancePath keys and update the KSPInstanceCount key.

**Comment by linuxgurugamer** [comment]
I had the same problem, although I had deleted the first one (in the example above, I deleted KSP-A)
In addition to changing the count, I had to rename both the KSPInstanceName_1 to KSP_InstanceName_0 and KSPInstancePath_1 to KSPInstancePath_0

**Comment by 7ranceaddic7** [comment]
Actually, if you recreate a missing install with just the following four items:
KSP_Install
     GameData
     readme.txt (just copy from a valid install)

Run CKAN and it will recognize the path as valid.  Then delete.

**Comment by tjanke42** [comment]
Thanks for the workaround; good to know.

Cheers,
Tim

--
Tim Janke
408.472.1294
