### ISSUE TITLE
Refer to new Mono version in Wiki

### ISSUE THREAD

**Issue by bax-** [KSP-CKAN/CKAN-support#75]
Hey there!

Mono has been updated to 3.12.0:

http://www.mono-project.com/download/#download-mac
http://www.mono-project.com/docs/about-mono/releases/3.12.0/

**Comment by Ippo343** [comment]
Hey @bax- ! Thanks for telling us. The wiki can be edited by anyone, I encourage you to add this to the wiki yourself :)

Cheers!
