### ISSUE TITLE
"Go To Changes" blacked out

### ISSUE THREAD

**Issue by aslatas** [KSP-CKAN/CKAN-support#76]
I'm not sure what causes this issue. After ticking a few check-boxes, the button functions. At some point in adding mods, it is blacked out, and the program won't allow me to make the change.

**Comment by mgsdk** [comment]
It can happen if you select two mods which conflict which each other. Currently, CKAN is not too good at informing the user of this.

**Comment by Ippo343** [comment]
Hi @aslatas , this might be caused by the fact that you have selected either:
* two incompatible mods
* a mod whose dependencies can't be satisfied completely.

I agree that the GUI needs better readouts about these situations...
