### ISSUE TITLE
Downloads time out

### ISSUE THREAD

**Issue by Quantum-Incident** [KSP-CKAN/CKAN-support#77]
I am having a problem with file downloads timing out, is there a way to download the files outside of ckan, so all ckan has to do is install them?

ps I am running on OSX using mono

**Comment by Ippo343** [comment]
Afraid not. CKAN needs to register them as cached, and will only do that if it has downloaded them itself (as far as I know, at least).

What downloads are timing out? We'd need better reproduction steps to help you out.

**Comment by Ippo343** [comment]
Er, didn't mean to close this one yet. Wrong button is wrong.

**Comment by Quantum-Incident** [comment]
The Blizzy toolbar is timing out along with SCANsat

**Comment by Dazpoet** [comment]
Unable to reproduce in both OS X and Windows 7, I am however using a 100Mbit connection might have have an effect.

Tests done using CKAN 1.6.5.

**Comment by Dazpoet** [comment]
Unable to reproduce using 1.6.6 aswell on both OS X and Win 7. I'll close this for now but feel free to re-open it if the problem persists.
