### ISSUE TITLE
.NET error when opening CKAN. 

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#82]
_From @jonassm on January 25, 2015 21:2_

Error: http://pastebin.com/cDwQfAEw

_Copied from original issue: KSP-CKAN/CKAN#767_

**Comment by Ippo343** [comment]
_From @hakan42 on January 25, 2015 21:38_

Looks like an old version of CKAN, the WTFPL was added to ckan some time ago. 

Could you download the latest release and try again, please?

**Comment by Ippo343** [comment]
_From @jonassm on January 26, 2015 8:49_

This occured in the newest relesae, however i had used a lot of older releases before, i tried like 4 different in 10 minutes, maybe that has something to do with it. I used the different releases because of this: https://github.com/KSP-CKAN/CKAN/issues/766

**Comment by Ippo343** [comment]
_From @sephie on January 26, 2015 16:56_

Same here. 1.5.6 is the only version of this great app that I've used and now it's crashing. First happened when I pressed Refresh and then on startup.

edit: removed large error report, see first post

**Comment by Ippo343** [comment]
_From @sephie on January 26, 2015 17:10_

On refresh:
```
Failed to connect to repository. Exception: The given key was not present in the dictionary.
```

**Comment by Ippo343** [comment]
_From @hakan42 on January 26, 2015 17:18_

We seem to have some strange content in the repository that makes the "upgrade" step fail.

Investigating...

**Comment by Ippo343** [comment]
_From @sephie on January 26, 2015 17:44_

It works again for me. After the crash alert on startup, hit 'continue' and then perform a refresh and everything will be back to normal.

**Comment by Dazpoet** [comment]
This problem appears resolved and as such I'm closing the issue.
