### ISSUE TITLE
Support forum?

### ISSUE THREAD

**Issue by Wizarth** [KSP-CKAN/CKAN-support#84]
Reviewing how many people pop into IRC, ask a question, then leave before getting a response, perhaps we should look into a support forum. I know GitHub issues are kind-of a forum, so maybe it's redundant, but I'm seeing a lot of similar questions asked (usually about CKAN not detecting manually installed mods).

Unfortunately I'm not seeing any way to have a forum hosted by GitHub.

In terms of setting up our own forum, [Discourse](http://www.discourse.org/) seems to be getting good press.

**Comment by hakan42** [comment]
Stupid question, but isn't that what our thread over at the KSP forums is for?

**Comment by Ippo343** [comment]
I think that @Wizarth meant a whole forum just for CKAN, instead of a single thread.
I'm not against it, but don't count me in for moderation... :P

**Comment by Wizarth** [comment]
Yeah that's what I mean. People seem to be put off by "Issues", especially for small questions. And it's difficult to read long threads on a forum, so having smaller threads on a dedicated forum might be more useful.

Just wanted to float the idea out there, as IRC has evolved to be less interactive now that the initial bursts of development have passed.

**Comment by hakan42** [comment]
Honestly, the most I could spring for would be a sub-forum on the main KSP forum, if they would configure such a thing. Main reason being that our manpower is stretched thin already, and that I would not like to split the community between the main forum and "ours". 

Let's wait for the dust to settle after the community manager changeover (in the last devnotes), and then we contact the new one. Peter, would you be willing to take on that?

**Comment by Dazpoet** [comment]
I think this could (should?) be adressed by extending the wiki to include normal errors. I've done some startup work on a [basic troubleshooting guide](https://github.com/KSP-CKAN/CKAN-support/wiki/Basic-troubleshooting) but keeping it up to date have sadly not been a priority of mine and it's hard to condense *everything* into an easily readable format.

Maybe it would be an idea to have a wikipage on github detailing what kind of information an error report should contain as to make it easier to help people. Error reports on the form *"Thing x gives me an error, please help"* are oftentimes much harder to handle than *"Thing x gives me an error <copy of error> when doing steps 1 and 2. I tried solution q and the error persists, please advise"*

If we consistently link to the information on how we want errors to be reported people who frequent the CKAN thread and github repos are bound to pick it up and start linking it themselves to people asking for help. If said information also includes links to the basic troubleshooting guide and installation guides people might even solve their own problems before we get to them :)

I'd be glad to create a short page on how people should report errors but we'd have to agree on what's important. Some quick thoughts from me are:

- What was expected outcome and what happened
- Do you get an error message, if so what does it say
- What is your CKAN version and your OS
- Can the problem be reproduced and if so, how
- Does the problem persist in both GUI and Commandline
- When applicable, what is the output of `mono --version`
- What, if any are applicable, solutions from [basic troubleshooting](https://github.com/KSP-CKAN/CKAN-support/wiki/Basic-troubleshooting) have you tried
