### ISSUE TITLE
Please allow for Github TAG filtering on release for netkan

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-CKAN/CKAN-support#85]
I am currently unable to use Netkan automattion because of the way I do my releases.  I essentially release two indivudal mods from one base.  TestFlight-Stock and TestFlight-RealismOverhaul.  They both come from the same base code, but I have an automated build system that, based on the tag I put for the release, builds one setup or the other.  When I release my mod I release both a Stock and a RealismOverhaul setup for whichever version of my mod is being released.

Since they both come from the same project and are both released at once on my Github, there isn't a way for me to point a netkan to my release page and have things work automatically.  Currently I am having my build system auto-generate .ckan files for both releases, and then I am going to manually submit a PR for each release.  That is a pain for me to do and for you as well, so I am proposing an addition to your netkan system to allow me to specify a *tag filter* that would be used to match releases.  All my releases have git tags that match this format: `major.minor.build.patch-configuration` so for example for this latest release I had 0.4.6.1-Stock and 0.4.6.1-RealismOverhaul.  My build system parses the string to get the pieces it needs to determine what to do.  If I could point a netkan to my releases page and specify a string to filter on, then I could setup two netkans one with a filter of "Stock" and the other with a filter of "RealismOverhaul".

**Snipped from a discussion on a PR**

>As for automation, I assume your current way of working through Github with Netkan is you search the releases for the latest one? Maybe if you added the ability to specify a string to filter on, that would work.

>Here is my releases page: https://github.com/jwvanderbeck/TestFlight/releases
>If you note there are two releases for 0.4.6.1 so if you just grabbed the latest one you wouldn't get them both. On CKAN I am essentially treating TestFlight as two separate mods. One TestFlight-Stock and the other TestFlight-RealismOverhaul. If I could make the Netkan point to my releases page AND specify a filter string to be checked against the TAG then I could set up two netkans one with a filter of "RealismOverhaul" and one with a filter of "Stock" and then when it queried my release page for the latest release that has a tag containing that string, it would match.

**Comment by hakan42** [comment]
This would take a filter argument to the github URL. Need to think more on this, though :smiling_imp:

**Comment by jwvanderbeck** [comment]
While to the best of my knowledge you can't generate a URL for a partial tag search, you can go read in [This Page](https://github.com/jwvanderbeck/TestFlight/tags) and then parse the page for the tag and link

**Comment by hakan42** [comment]
There is a JSON data dump of your releases available which we already use.  It's a matter of implementing the right filter and coming up with a nice syntax for the netkan file...

But, as usual,  there is that matter with only 24 hours in a days. Or was it 36?

**Comment by jwvanderbeck** [comment]
I'm curious if anything happened on this?

I am trying to refactor my mod into a core Plugin and separate Config Packs, and I can't seem to find any way to do it other than having multiple GitHub projects which is a real maintenance nightmare.

**Comment by hakan42** [comment]
Oops, I lost view of this a bit. I might take another look at it but it would take a few days at least until I find time for it.
