### ISSUE TITLE
CKAN.URLHandlers error

### ISSUE THREAD

**Issue by madsailor** [KSP-CKAN/CKAN-support#89]
I launch the CKAN gui from command line in Ubuntu using mono.  CKAN seems to work fine, but an error is thrown in the terminal window when the GUI initializes: 18443 [1] ERROR CKAN.URLHandlers (null) - Error: Parsing Error: Could not parse file ~/.local/share/applications/mimeapps.list.  The mimeapps.list file does exist on my system.  This is with v1.6.0 (commit d457c0d), though it happened in previous versions as well.

**Comment by darqen27** [comment]
Getting this same error on Ubuntu 14.04 LTS, everything is updated.

CKAN.EXE freezes the whole computer if I try to click anything in the mods list afterwards and I have to break the program to unfreeze my whole computer

**Comment by Dazpoet** [comment]
Pure shot in the dark here but could this be related to https://github.com/KSP-CKAN/CKAN/issues/793 and https://github.com/KSP-CKAN/CKAN-support/issues/58 seeing as the file is located in a hidden folder?

**Comment by darqen27** [comment]
I have KSP_linux installed to the desktop on ubuntu, and ckan never asked where my install was as I just dropped it into KSP's folder

**Comment by ActivKino** [comment]
I'm getting the same issue, running Linux Mint and the latest dev version of CKAN. On my end, I don't seem to be seeing any adverse effects from it, but it does happen every time I run it. Dazpoet recommended I try it with sudo, and it actually explodes pretty consistently with a super long error message, does not load the GUI, and the terminal process hangs.

**Comment by pjf** [comment]
I *also* get this, but I haven't noticed it cause any problems. Looking at the code (`CKAN-GUI/URLHandlers.cs`) if we can't parse the file we just do nothing, so if we're seeing other problems this message may be a false alarm. I wouldn't call this an error-level condition, it'd be a warning at best.

I'll patch the code so it's not quite as high a priority message from our logging system, and expand it a little to make it clear what's going on.

**Comment by darqen27** [comment]
Making the error less scary doesnt fix the client from hanging

**Comment by pjf** [comment]
> Making the error less scary doesnt fix the client from hanging.

No, but since there's nothing in that section of code that can cause a hang when the error occurs (since the handler installation is just skipped), I'm very confident that any hang you do see is unrelated.

Running `ckan.exe gui --verbose` will give you lots of output, and a much better indication as to where any hangs are happening. `ckan.exe gui --debug` will give you even more.

**Comment by darqen27** [comment]
okay, understood, thanks
