### ISSUE TITLE
repositry update error

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-support#9]
_From @seb62085 on December 18, 2014 23:14_

when clicking refresh, or updating the repository URL i get an error....

 ************** Exception Text ************** The following inconsistecies were found: AJE requires FerramAerospaceResearch but nothing provides it   at CKAN.SanityChecker.EnforceConsistency(IEnumerable`1 modules, IEnumerable`1 dlls)    at CKAN.RegistryManager.Save()    at CKAN.KSP.ScanGameData()    at CKAN.Main.UpdateRepo()    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)    at System.Windows.Forms.ToolStripItem.HandleMouseU

however after updating the repository via command line... it now updates just fine.

_Copied from original issue: KSP-CKAN/CKAN#632_

**Comment by Ippo343** [comment]
Hey @seb62085 , does this still happen using the latest release? Closing in the meantime.

**Comment by seb62085** [comment]
nope...  works now
