### ISSUE TITLE
How to handle changes in version scheme

### ISSUE THREAD

**Issue by mgsdk** [KSP-CKAN/CKAN-support#91]
I just noticed that OTHOAB's texture pack isn't installable, since it points to an old version (06.01) while the current is 0.12. Both versions are in the metadata but the wrong one is chosen due to the higher version number. How should we handle issues such as this? I know I can install from a ckan file, but I don't think this is a solution for the end user.

**Comment by Dazpoet** [comment]
I can't even find another version than 0.12, I guess someone solved it by deletion?

Funnily enough it seems the packs where updated just 4 days ago in CKAN-meta, but they're still 0.12 and ksp version 0.90.

**Comment by mgsdk** [comment]
Closing as there only is one version available now as mentioned by @Dazpoet.
