### ISSUE TITLE
Show CKAN version on GUI and provide link to download pages on github

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN-support#94]
1. On the About screen, it doesn't say the version of CKAN that you are running. That would be helpful
2. A "nice" thing would be a button to check for updates. This would be less necessary if the version was listed in the About screen
3. The CKAN home page should have either a "Download latest copy" or at least a link to the Releases page (https://github.com/KSP-CKAN/CKAN/releases). Right now it takes a number of clicks and hunting to find the right page

**Comment by AlexanderDzhoganov** [comment]
As of v1.6.3 CKAN can update itself.
