### ISSUE TITLE
GUI and command line don't agree on what mods to recommend

### ISSUE THREAD

**Issue by aw1621107** [KSP-CKAN/CKAN-support#95]
Seems that the CKAN GUI and command line sometimes disagree on what mods to install from the "Recommended" list.

This was done with the most recent release of the ckan.exe executable on OS X 10.10.2.

Running 

    mono ~/Applications/ckan.exe install RealismOverhaul

Yields the following list of mods to install:
```
About to install...

 * RealismOverhaul v8.1.1 (cached)
 * RSSTexturesDDS2048 1.0 (cached)
 * ActiveTextureManagement-x86-Aggressive 4-3 (cached)
 * TACLS-Config-RealismOverhaul v8.1.1 (cached)
 * AdvancedJetEngine 2.0.3 (cached)
 * FerramAerospaceResearch v0.14.6 (cached)
 * ModuleManager 2.5.9 (cached)
 * RealFuels rf-v8.4 (cached)
 * CrossFeedEnabler v3.2 (cached)
 * KerbalJointReinforcement v3.1.1 (cached)
 * ModuleRCSFX v3.5 (cached)
 * RealSolarSystem v8.5 (cached)
 * DDSLoader 1.8.0.0 (cached)
 * CustomBiomes-Data-RSS v8.5 (cached)
 * CustomBiomes v1.7.2 (cached)
 * Toolbar 1.7.8 (cached)
 * BetterBuoyancy v1.1 (cached)
 * ConnectedLivingSpace 1.1.1.0 (cached)
 * DeadlyReentry v6.4.0 (cached)
 * EngineIgnitor-Unofficial-Repack 3.4.1.1-1 (cached)
 * FilterExtensions 1.17 (cached)
 * FShangarExtender 3.0 (cached)
 * KSP-AVC 1.1.5.0 (cached)
 * MechJeb2 2.4.2 (cached)
 * ProceduralDynamics v0.9.3 (cached)
 * ProceduralFairings v3.11 (cached)
 * ProceduralParts v1.0.2 (cached)
 * RealChute 1.2.6.3 (cached)
 * RealPlume v8.1.1 (cached)
 * SmokeScreen 2.5.3 (cached)
 * RemoteTech v1.6.3 (cached)
 * TACLS v0.10.2b (cached)
 * TextureReplacer 2.2.5 (cached)
 * TweakScale v1.50 (cached)
```

While doing the same in the GUI (installing all recommended mods and no suggested mods):

![screen shot 2015-02-27 at 5 55 33 pm](https://cloud.githubusercontent.com/assets/566572/6422725/d9973740-bea9-11e4-9514-339b7fbf7eb5.png)

(sorry about the picture, seems I can't copy/paste the output)

Some mods are missing from the latter image, such as TACLS, Active Texture Management, and EngineIgnitor.

**Comment by aw94** [comment]
May be sort of fixed in 1.6.6.0? TACLS RSS config shows up properly. However, RSS now automatically includes RSS Textures 2048x1024, and ATM doesn't seem to be showing up still. Possibly something to do with the changes made [here](https://github.com/aw94/CKAN-core/commit/72577c59d88e29ec1f326cbed58b35921fbb5676)?
