### ISSUE TITLE
install --headless doesn't automatically install necessary mods if > 2 mods provide the same functionality

### ISSUE THREAD

**Issue by aw94** [KSP-CKAN/CKAN-support#96]
mono ckan.exe install RealismOverhaul asks for the user to select from 6 different RSSTextures packages, 4 different ATM packages, and 2 different TACLS configs. The install proceeds normally.

mono ckan.exe install RealismOverhaul --headless installs everything "normally", but doesn't include RSSTextures or ATM installs, but installs the TACLS configs fine. Thus, next time ckan.exe is invoked the registry is loaded in an inconsistent state because RSSTextures is a dependency for RSS, which is a dependency for RO.

An example can be seen [here](http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20NetKAN%20metadata/580/console), where the RO build failed despite the RSS metadata correctly specifying the missing package.

**Comment by aw94** [comment]
This may be around the area that causes this behavior? https://github.com/KSP-CKAN/CKAN-core/blob/158e54c95d7b1a364cd09df0f2a3705fdc2a47d5/Relationships/RelationshipResolver.cs#L190

**Comment by AlexanderDzhoganov** [comment]
The `--headless` mode is currently used only by our build bot and isn't meant for production use. Feel free to improve on it and make a PR :)

**Comment by aw94** [comment]
I'll give it a shot. Don't have C# experience or a windows machine to build on, but I'll see if I can make a change that I think is likely to work.
