### ISSUE TITLE
Feature request: A GUI button for installing .ckan files

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#97]
Now that metapackages are a thing it would be nice to have a button in the GUI to install redistributed .ckan files.

Since I assume that all regular mod handling is expected to go through the normal channels I would recommend that said button only works for .ckan files that are "kind" : "metapackage" but that's just my thought and maybe there's a better way of doing things :)

**Comment by AlexanderDzhoganov** [comment]
Implemented in 1.6.1.
